# Generated by Django 4.2.30 on 2026-07-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('username', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=32)),
                ('accent_color', models.CharField(choices=[('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('green', 'Green')], default='blue', max_length=32)),
                ('selected_companion', models.CharField(choices=[('astro', 'Astro'), ('nova', 'Nova'), ('ember', 'Ember')], default='astro', max_length=32)),
                ('show_companion', models.BooleanField(default=True)),
                ('companion_speech_bubbles', models.BooleanField(default=True)),
                ('companion_animation_speed', models.IntegerField(choices=[(1, 'Normal'), (2, 'Fast'), (3, 'Faster')], default=1)),
                ('companion_sound_effects', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('habit_reminders', models.BooleanField(default=True)),
                ('goal_reminders', models.BooleanField(default=True)),
                ('reading_reminders', models.BooleanField(default=True)),
                ('budget_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('monthly_reports', models.BooleanField(default=True)),
                ('habit_reminder_time', models.TimeField(default='09:00')),
                ('goal_reminder_time', models.TimeField(default='18:00')),
                ('reading_reminder_time', models.TimeField(default='20:00')),
                ('dashboard_layout', models.CharField(choices=[('grid', 'Grid'), ('compact', 'Compact')], default='grid', max_length=32)),
                ('show_widgets', models.JSONField(blank=True, default=dict)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('show_achievements_public', models.BooleanField(default=True)),
                ('show_stats_public', models.BooleanField(default=True)),
                ('show_reading_public', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=32)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('profile_completion_percent', models.IntegerField(default=0)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('milestone_type', models.CharField(max_length=64)),
                ('icon_name', models.CharField(max_length=64)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('email_change', 'Email Changed'), ('device_login', 'Device Login'), ('profile_update', 'Profile Updated'), ('settings_change', 'Settings Changed')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('verify', 'Email Verification'), ('reset', 'Password Reset')], default='verify', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='accounts_em_email_253133_idx'), models.Index(fields=['otp'], name='accounts_em_otp_f89c28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(max_length=64)),
                ('achievement_type', models.CharField(choices=[('habit', 'Habit'), ('mood', 'Mood'), ('sleep', 'Sleep'), ('focus', 'Focus'), ('reading', 'Reading'), ('expense', 'Expense'), ('journal', 'Journal'), ('goal', 'Goal')], max_length=32)),
                ('unlock_condition', models.JSONField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_name')},
            },
        ),
    ]
