# Generated by Django 4.2.30 on 2026-07-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_reminders', models.BooleanField(default=True)),
                ('goal_reminders', models.BooleanField(default=True)),
                ('mood_reminders', models.BooleanField(default=True)),
                ('sleep_reminders', models.BooleanField(default=True)),
                ('focus_reminders', models.BooleanField(default=True)),
                ('reading_reminders', models.BooleanField(default=True)),
                ('expense_reminders', models.BooleanField(default=True)),
                ('study_reminders', models.BooleanField(default=True)),
                ('ai_motivation_messages', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=True)),
                ('monthly_replay', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('habit_reminder', 'Habit Reminder'), ('goal_reminder', 'Goal Reminder'), ('study_reminder', 'Study Reminder'), ('sleep_reminder', 'Sleep Reminder'), ('reading_reminder', 'Reading Reminder'), ('expense_reminder', 'Expense Reminder'), ('time_capsule_reminder', 'Time Capsule Reminder'), ('weekly_summary', 'Weekly Summary'), ('monthly_replay', 'Monthly Life Replay'), ('ai_motivation', 'AI Motivation Message'), ('achievement_unlocked', 'Achievement Unlocked'), ('streak_milestone', 'Streak Milestone'), ('budget_warning', 'Budget Warning'), ('goal_deadline', 'Goal Deadline'), ('new_insight', 'New Insight Generated')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('icon', models.CharField(default='Bell', max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
