# Generated by Django 4.2.30 on 2026-07-08 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(blank=True, max_length=140)),
                ('total_pages', models.PositiveIntegerField(default=1)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('finished_on', models.DateField(blank=True, null=True)),
                ('reading_goal_pages_per_day', models.PositiveSmallIntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('both', 'Both')], default='expense', max_length=12)),
                ('color', models.CharField(default='blue', max_length=24)),
                ('icon', models.CharField(default='💰', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('career', 'Career'), ('health', 'Health'), ('finance', 'Finance'), ('education', 'Education'), ('relationship', 'Relationship'), ('other', 'Other')], default='personal', max_length=24)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('target_value', models.PositiveIntegerField(default=100)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='not_started', max_length=16)),
                ('color', models.CharField(default='blue', max_length=24)),
                ('icon', models.CharField(default='🎯', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('health', 'Health'), ('study', 'Study'), ('work', 'Work'), ('fitness', 'Fitness'), ('finance', 'Finance'), ('wellness', 'Wellness'), ('other', 'Other')], default='other', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('target_per_week', models.PositiveSmallIntegerField(default=7)),
                ('color', models.CharField(default='cyan', max_length=24)),
                ('icon', models.CharField(default='spark', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pages_read', models.PositiveIntegerField()),
                ('read_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trackers.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_on'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('bad', 'Bad')], max_length=16)),
                ('emoji', models.CharField(default='🙂', max_length=16)),
                ('label', models.CharField(max_length=60)),
                ('score', models.PositiveSmallIntegerField(default=5)),
                ('note', models.TextField(blank=True)),
                ('logged_on', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_on'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='trackers.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LifeExperienceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('habit', 'Habit'), ('reading', 'Reading'), ('focus', 'Focus'), ('goal', 'Goal'), ('wellness', 'Wellness')], max_length=24)),
                ('source_id', models.PositiveBigIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(max_length=160)),
                ('earned_on', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='trackers.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=120)),
                ('session_type', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('deep_work', 'Deep Work'), ('study', 'Study'), ('review', 'Review')], default='pomodoro', max_length=24)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=25)),
                ('completed', models.BooleanField(default=False)),
                ('productivity_rating', models.PositiveSmallIntegerField(default=5)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('digital', 'Digital Wallet'), ('other', 'Other')], default='cash', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='trackers.expensecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expense Entries',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slept_on', models.DateField(default=django.utils.timezone.localdate)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('quality', models.PositiveSmallIntegerField()),
                ('bedtime', models.TimeField(blank=True, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-slept_on'],
                'indexes': [models.Index(fields=['user', 'slept_on'], name='trackers_sl_user_id_5b30df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sleepentry',
            constraint=models.UniqueConstraint(fields=('user', 'slept_on'), name='unique_sleep_entry_per_day'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['user', 'read_on'], name='trackers_re_user_id_d4455e_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['book', 'read_on'], name='trackers_re_book_id_803f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'logged_on'], name='trackers_mo_user_id_00f739_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'mood'], name='trackers_mo_user_id_ad93f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(fields=('user', 'logged_on'), name='unique_mood_entry_per_day'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'completed'], name='trackers_mi_goal_id_519631_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'due_date'], name='trackers_mi_goal_id_5ffe90_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['goal', 'order'], name='trackers_mi_goal_id_4d8c88_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeexperienceevent',
            index=models.Index(fields=['user', 'earned_on'], name='trackers_li_user_id_b00463_idx'),
        ),
        migrations.AddIndex(
            model_name='lifeexperienceevent',
            index=models.Index(fields=['user', 'source'], name='trackers_li_user_id_c76dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='lifeexperienceevent',
            constraint=models.UniqueConstraint(fields=('user', 'source', 'source_id', 'earned_on', 'reason'), name='unique_xp_event_per_source_day'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'entry_date'], name='trackers_jo_user_id_24b98e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_pinned'], name='trackers_jo_user_id_fb1309_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_favorite'], name='trackers_jo_user_id_a173ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('title__gt', '')), fields=('user', 'entry_date', 'title'), name='unique_journal_per_day_title'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['user', 'completed_on'], name='trackers_ha_user_id_f99c51_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'completed_on'], name='trackers_ha_habit_i_03abad_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitcompletion',
            constraint=models.UniqueConstraint(fields=('habit', 'completed_on'), name='unique_habit_completion_per_day'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'category'], name='trackers_ha_user_id_43bfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='trackers_ha_user_id_f067ab_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='trackers_go_user_id_841c53_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'deadline'], name='trackers_go_user_id_e08997_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'category'], name='trackers_go_user_id_ea5fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'priority'], name='trackers_go_user_id_1e83a8_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'started_at'], name='trackers_fo_user_id_536770_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'subject'], name='trackers_fo_user_id_1941e5_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'occurred_on'], name='trackers_ex_user_id_1e8f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'entry_type'], name='trackers_ex_user_id_4a46ce_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['category', 'occurred_on'], name='trackers_ex_categor_b2bfe4_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseentry',
            index=models.Index(fields=['user', 'payment_method'], name='trackers_ex_user_id_76a2a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_expense_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'title'], name='trackers_bo_user_id_881368_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['user', 'finished_on'], name='trackers_bo_user_id_e47a54_idx'),
        ),
    ]
